### ISSUE TITLE
worker initialization failed: there is no package called ‘RRgeo’

### ISSUE THREAD

**Issue by dru1889** [pasraia/RRdtn#6]
Hi,

When I run ENFA modeling by using the following codes based on the example data from ENphylo code&data 2.zip

##### ENFA ######
enfa_test<-ENphylo_modeling(input_data=DATA_FULL[k],
                            input_mask=MASK_FULL,
                            tree=tree,
                            obs_col="OBS",
                            time_col="TIME_factor",
                            min_occ_enfa=npoints-1,
                            eval_metric_for_imputation="AUC",
                            output_options = "best",
                            eval_threshold=0.5)

I got an error showing that "worker initialization failed: there is no package called ‘RRgeo’’

I would like to install it from the internet by searching "R package RRgeo", but can't get where I can download and install it.
Could you please give me some suggestions about it?
For the RRgeo, is it a R package? or something else?

Thanks

Best,
dru1889

**Comment by pasraia** [comment]
Dear dru1889,
Thanks for your interest in our software and for reaching out to me. 
The issue has been resolved, good luck with your research!

**Comment by dru1889** [comment]
Thanks for your fixing the code.

BTW, can you figure out if I want to set up the time_col as NULL. what other parameters or input_data should be formatted? I set it as NULL, and use "Rangifer_tarandus" data to run ENphylo_modeling, then the error shows as "Error in colMeans(x, na.rm = TRUE) : 'x' must be numeric".
